# Generated by Django 5.1.2 on 2025-08-11 18:28

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("judge", "0004_userproblemstat_solution"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="userproblemstat",
            unique_together={("user", "problem")},
        ),
    ]
